//
// Created by adrien on 25/03/23.
//

#ifndef RAYTRACER_SETTINGS_H
#define RAYTRACER_SETTINGS_H

#define GAMMA_CORRECTION_ENABLED true
#define PRINT_DEBUG_INFO true
#define LEVERAGE_MULTITHREADING true

#endif //RAYTRACER_SETTINGS_H
